<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Template.Webapi.Netcore.Infrastructure.Data__o_Infrastructure.Data_dotnet_new_classlib__n_Template.Webapi.Netcore.Infrastructure.Data</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
